### PR TITLE
Add Filipino language to React and React Native SDK

### PR DESCRIPTION
**Pull request by warengonzaga**
## Add Filipino Language Support

Credits to Filipino community members.
- [@Skippergemx](https://github.com/Skippergemx)
- [YirenNing24/](https://github.com/YirenNing24/)

Kudos to the amazing community help from [Web3 Philippines](https://web3philippines.org)

### CODE REVIEW

**Comment by warengonzaga** [comment]
Updated from `fil` into `tl` as per standard code.

**Comment by warengonzaga** [comment]
Hey @iketw I'm still working on the update, please don't yet merge this.

**Comment by warengonzaga** [comment]
Hey @iketw I'm done with the translation for the React SDK kindly review it. Thank you for waiting!
Let me know if this is correct.

**Review by jnsdls — APPROVED** [review]
LGTM

**Comment by jnsdls** [comment]
hey @warengonzaga sorry for the long delay here, it looks like since you created this new strings to translate were added in `/react` - could you check the object of strings for completeness (and update the necessary new strings) and then we can get this merged

**Comment by warengonzaga** [comment]
> hey @warengonzaga sorry for the long delay here, it looks like since you created this new strings to translate were added in `/react` - could you check the object of strings for completeness (and update the necessary new strings) and then we can get this merged

I'm able to find the missing string, pushed the changes.

**Pull request merged**
