### PR TITLE
Fix typo in comments

### PR DESCRIPTION
**Pull request by vuittont60**
Fix typo in comments

### CODE REVIEW

**Comment by kien-ngo** [comment]
@vuittont60 thanks for the help 🙌

**Comment by kien-ngo** [comment]
@vuittont60 Can you add a changeset by running `pnpm changeset`

**Comment by vuittont60** [comment]
@kien-ngo I added the changeset, and is that right? Please help me to review again. Thank you very much.

**Comment by kien-ngo** [comment]
Looks good ty

**Pull request merged**
