### PR TITLE
Isaac/migrate paper react components (OLD)

### PR DESCRIPTION
**Pull request by IDubuque**
## Problem solved

Merging @paperxyz/react-client-sdk into @thirdweb-dev/react

## Changes made

- [x] Migrate files from @paperxyz/react-client-sdk to @thirdweb-dev/react
- [x] Update @paperxyz/react-client-sdk files to use @thirdweb-dev/payments

## How to test

- [x] Checkout component in paper-web sdk/2022-08-12/examples/checkout-with-card
- - transactionId: be48be00-868d-4973-abe3-9851f3e8d136
- - iframe: data-thirdweb-sdk-version="@thirdweb-dev/react@0.0.0-dev-b9da519-20231101165627”
- - [transaction hash ](https://mumbai.polygonscan.com/tx/0xbc92a51fba12a63e4642491fe3a568e15e63acce4c63ad6b1cfaca4ceed288ac)

### CODE REVIEW

**Comment by IDubuque** [comment]
moving this to [new branch](https://github.com/thirdweb-dev/js/pull/1913)

**Comment by jnsdls** [comment]
done in #1913

**Pull request closed without merging**
