### PR TITLE
[ReactNative] Sign in with email/phone number

### PR DESCRIPTION
**Pull request by iketw**
Magic implementation

### CODE REVIEW

**Comment by rowbot-weisguy** [comment]
Hi @iketw! Our team wants to use the React Native implementation of the Magic wallet and we're stoked about what you're working on. Let me know if we can help you test it and we'll be happy to give feedback. I've reached out on the support channel in Discord as well.

**Comment by iketw** [comment]
> Hi @iketw! Our team wants to use the React Native implementation of the Magic wallet and we're stoked about what you're working on. Let me know if we can help you test it and we'll be happy to give feedback. I've reached out on the support channel in Discord as well.

[rowbot-weisguy](https://github.com/rowbot-weisguy), thanks for reaching out! Of course, I'm landing this today. After it lands you should be able to try it out by using `@thirdweb-dev/react-native@nightly`

Next steps for email/phone is to white label the UI and stop using magic's UI

**Comment by rowbot-weisguy** [comment]
@iketw yep! We're using the React Native SDK to log in with MetaMask on our React Native app. We were also using Web3Auth for provisioning wallets via email / social login methods, but they can't point to the same wallets when logging in between different devices, so we started evaluating alternatives. We knew we liked working with ThirdWeb's SDK so far so we checked to see what Wallet connection types your SDK supports and lo and behold, `Magic Link` was listed on your Wallet [docs page](https://portal.thirdweb.com/wallet) and we got interested. 

Happy to chat about our experience, but the gist is that Web3 tooling is in constant flux, and React Native support almost always seems to be bare minimum. So far working with ThirdWeb's SDK has been a lot better for our React Native devs and it feels like you're setting the bar for tooling in this space, so it's great to see quick followup on adding React Native support exactly at the time we were evaluating Magic Link. We're going to be operating mobile-first for a lot more development efforts just to ensure we are doing technical evaluation starting from the most constrained point.

I'm about to take some time off starting Tuesday so I'll be checking in on the Magic Link support on June 5th. Cheers!

**Comment by iketw** [comment]
> @iketw yep! We're using the React Native SDK to log in with MetaMask on our React Native app. We were also using Web3Auth for provisioning wallets via email / social login methods, but they can't point to the same wallets when logging in between different devices, so we started evaluating alternatives. We knew we liked working with ThirdWeb's SDK so far so we checked to see what Wallet connection types your SDK supports and lo and behold, `Magic Link` was listed on your Wallet [docs page](https://portal.thirdweb.com/wallet) and we got interested. 
> 
> Happy to chat about our experience, but the gist is that Web3 tooling is in constant flux, and React Native support almost always seems to be bare minimum. So far working with ThirdWeb's SDK has been a lot better for our React Native devs and it feels like you're setting the bar for tooling in this space, so it's great to see quick followup on adding React Native support exactly at the time we were evaluating Magic Link. We're going to be operating mobile-first for a lot more development efforts just to ensure we are doing technical evaluation starting from the most constrained point.
> 
> I'm about to take some time off starting Tuesday so I'll be checking in on the Magic Link support on June 5th. Cheers!

Glad to hear the SDK is being useful! And yes, let's schedule some time to chat when you're back, we're always looking for feedback to improve our tooling, and what better feedback than from devs using it. Enjoy your PTO!

**Pull request merged**
