### PR TITLE
[CLI] Modify auto-update process with flag and caching

### PR DESCRIPTION
**Pull request by adam-maj**
4 changes in this PR:
- Added `--skip-update-check` flag that will always skip checking for updates
- Added disk caching to save the timestamp of the last update check. Update checks won't happen again if there has already been another check in the past 24h.
- Update check now happens on a `preAction` hook on the `program` rather than blocking the core flow of the main function. This means that it only runs on actual command calls and won't run on simpler runs like `thirdweb --version`
- Fixed broken link to `https://thirdweb.com/contracts` -> `https://thirdweb.com/explore` on deploy flow when there are no contracts in your repository.

### CODE REVIEW

**Comment by jnsdls** [comment]
pls no more flags

**Comment by joaquim-verges** [comment]
oooo the caching will be the game changer here, i'll test this in a bit

**Review by jnsdls — APPROVED** [review]
LGTM, couldn't break it

**Pull request merged**
