### PR TITLE
[SDK] Fix `invalid recipient` issue when deploy built-in contracts

### PR DESCRIPTION
**Pull request by kien-ngo**
## Problem solved

In the past we default `platform_fee_recipient` and `primary_sale_recipient` to AddressZero.
However due to a recent change in our smart contract extensions (PrimarySale & PlatformFee), AddressZero is no longer an accepted value for those fields.
So now we set the default value to the signer address.
ref: https://github.com/thirdweb-dev/contracts/pull/530

## Changes made

- [ ] Public API changes: list the public API changes made if any
- [x] Internal API changes: explain the internal logic changes

## How to test

- [x] Automated tests: link to unit test file
- [ ] Manual tests: step by step instructions on how to test

### CODE REVIEW

**Review by joaquim-verges — COMMENTED** [review]
wonder if we can make primary_sale_recipient optional now with this? it's required right now in the deploy metadata objects

**Comment by kien-ngo** [comment]
@joaquim-verges Hmm I'm not aware of any recent updates. Are you saying we don't need this PR?

**Comment by kien-ngo** [comment]
Ah I see, you were talking about the `primary_sale_recipient` and not `platform_fee_recipient`. Yeah I suppose we can leave it out

**Comment by joaquim-verges** [comment]
Oh I meant leave your changes, but make it optional in NFTDeployMetadata and co (default to address zero)

**Comment by kien-ngo** [comment]
Ty for the feedback. I'm updating the code plus adding a new test file!

**Comment by kien-ngo** [comment]
Added new test file here:

https://github.com/thirdweb-dev/js/blob/34ff60ac1a2acc9bfebde00dbeb9b91d64ecd5f3/packages/sdk/test/evm/recipient.test.ts

Also `primary_sale_recipient` is optional now. Pls have a look @joaquim-verges ty

**Review by joaquim-verges — APPROVED** [review]

**Pull request merged**
