### PR TITLE
v4? - functions based in viem

### PR DESCRIPTION
**Pull request by jnsdls**

### CODE REVIEW

**Comment by jxom** [comment]
👀

**Comment by jxom** [comment]
FYI - I think you guys will greatly benefit by using the [tree-shakable Actions](https://twitter.com/jakemoxey/status/1673846338067529730?s=20) internally. Will help a lot with keeping the bundle size slim for consuming code! For example, [`getBalance`](https://github.com/thirdweb-dev/js/blob/c0151f1783fd9049c61ea3b63a808175ec7e3764/packages/sdk-core/src/read/erc20/getBalance.ts#L45) itself only needs `readContract` from viem, so you can just import `readContract` and pass the `client` to it.

https://viem.sh/docs/clients/custom.html#tree-shaking

**Comment by jnsdls** [comment]
> 👀

u're everywhere ser

**Comment by jnsdls** [comment]
> 

ah this is *very* neat indeed. makes total sense

**Comment by jnsdls** [comment]
> FYI - I think you guys will greatly benefit by using the [tree-shakable Actions](https://twitter.com/jakemoxey/status/1673846338067529730?s=20) internally. Will help a lot with keeping the bundle size slim for consuming code! For example, [`getBalance`](https://github.com/thirdweb-dev/js/blob/c0151f1783fd9049c61ea3b63a808175ec7e3764/packages/sdk-core/src/read/erc20/getBalance.ts#L45) itself only needs `readContract` from viem, so you can just import `readContract` and pass the `client` to it.
> 
> https://viem.sh/docs/clients/custom.html#tree-shaking

ah this is very neat indeed. makes total sense

**Pull request closed without merging**
