### PR TITLE
[Dashboard] Fix minor layer issues

### PR DESCRIPTION
**Pull request by kien-ngo**
Before: 
image

After: 
image

---

## PR-Codex overview
This PR focuses on updating the layout and styling of the `supply-cards` and `page` components in the NFT dashboard, enhancing responsiveness and visual hierarchy.

### Detailed summary
- Changed the layout of the `supply-cards` from a horizontal (`flex-row`) to a vertical (`flex-col`) arrangement.
- Updated the heading in `page.tsx` from `font-bold text-xl` to `font-semibold text-2xl tracking-tight`.
- Adjusted the layout of the `page.tsx` content to use a grid and modified spacing classes for better alignment.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by MananTank — COMMENTED** [review]
Title and All buttons centered looks weird. 

Lets keep the title left aligned and all buttons in 2x2 grid - 2 buttons on row1, 2 buttons on row2

**Review by MananTank — CHANGES_REQUESTED** [review]
address comments

**Comment by kien-ngo** [comment]
* **#4928** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4928?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kien-ngo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by MananTank — APPROVED** [review]

**Comment by MananTank** [comment]
tweaked it a bit to:

**Pull request merged**
