### PR TITLE
[react-core] Add hook for creating direct listings in batch (Marketplace v3 only)

### PR DESCRIPTION
**Pull request by kien-ngo**
## Problem solved

Short description of the bug fixed or feature added

## Changes made

- [x] Public API changes: list the public API changes made if any
- [ ] Internal API changes: explain the internal logic changes

## How to test

- [ ] Automated tests: link to unit test file
- [x] Manual tests: step by step instructions on how to test

### CODE REVIEW

**Comment by kien-ngo** [comment]
Tested with a local repo.

**Review by jnsdls — APPROVED** [review]
LGTM

**Pull request merged**
