### PR TITLE
feat(connect-wallet): add transaction history page to connect modal UI

### PR DESCRIPTION
**Pull request by gregfromstl**
This pull request introduces new features and modifications to the transaction history feature within the connect modal UI. Key changes include:

- Addition of a transaction history page accessible from the connect modal's main menu, allowing users to view and manage their transaction history more effectively.
- Refactoring of transaction-related components to enhance code maintainability and readability. Specifically, renaming components related to 'BuyTxHistory' to 'PayTxHistory' to better reflect their functionality.
- Updates to locale files to include new translations for added labels such as 'payTransactions' and 'walletTransactions'.
- Integration of new navigation options within the connect modal, enabling seamless switching between different transaction views, including 'Fiat Transactions' and 'Wallet Transactions'.
- Ensuring that the transaction history page supports multiple languages, with updated English, Spanish, Japanese, and Vietnamese locale files.
- Improvements to UI components to ensure consistent styling and user experience across the transaction history pages.

These enhancements aim to provide users with an improved interface for managing their transaction histories, thereby enhancing overall user experience.

---

---

## PR-Codex overview
This PR adds a transaction history page to the connect modal UI, updates transaction-related texts, and refactors components for better organization.

### Detailed summary
- Added transaction history page to the connect modal UI
- Updated transaction-related texts like "transactions" to "payTransactions" and "walletTransactions"
- Refactored components related to transaction history to improve organization

> The following files were skipped due to too many changes: `packages/thirdweb/src/react/web/ui/ConnectWallet/TransactionsScreen.tsx`, `packages/thirdweb/src/react/web/ui/ConnectWallet/screens/WalletTransactionHistory.tsx`, `packages/thirdweb/src/react/web/ui/ConnectWallet/screens/Buy/tx-history/BuyTxHistory.tsx`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by gregfromstl** [comment]
* **#3718** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/3718?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gregfromstl and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by joaquim-verges — COMMENTED** [review]
How hard would it be to do tabs instead of a menu for view assets / view transactions? Its annoying to have that extra click no?

also when you back out of one of those screens, you go back to the main screen, skipping the menu.

"Fiat transactions" is a bit weird too, i assume those are all the Pay transactions and not just fiat? maybe call it Purchases / Transactions for now?

Also is there anything else we can show in the list of tx? like timestamp would be nice, maybe the chain as well ?

**Comment by gregfromstl** [comment]
I can try tabs instead. Not sure what to call pay transactions, I'd use "Pay" but not sure if end users are aware of that name.

Yeah we can add a timestamp for mined transactions but that's about it. We're already showing the chain

**Comment by joaquim-verges** [comment]
maybe add chain icon as well?

for the name maybe 'Purchases' ?

**Review by joaquim-verges — APPROVED** [review]
Looks good ser. Only thing I would do is switch the tabs around.

And also do tabs for assets as well 😁

**Comment by gregfromstl** [comment]
### Merge activity

* **Jul 17, 4:30 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/thirdweb-dev/js/3718) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

**Pull request merged**
