### PR TITLE
[Storage] Pre-compute IPFS hashes before uploading

### PR DESCRIPTION
**Pull request by adam-maj**

### CODE REVIEW

**Comment by jnsdls** [comment]
👀

**Review by joaquim-verges — APPROVED** [review]
ship it - doesnt touch anything (yet) so let's get it in and play with it

**Comment by adam-maj** [comment]
@joaquim-verges now it touches our core IPFS upload logic (actually added the precompute/return)

**Comment by adam-maj** [comment]
approved by @jnsdls

**Pull request merged**
