### PR TITLE
Add in-app wallet settings on project settings layout

### PR DESCRIPTION
**Pull request by MananTank**
## Problem solved

Short description of the bug fixed or feature added

---

## PR-Codex overview
The focus of this PR is to refactor the `Configure` component to `InAppWalletSettingsPage` and update its usage across the application.

### Detailed summary
- Renamed `Configure` component to `InAppWalletSettingsPage`
- Updated component props interface
- Updated component function declaration
- Updated component usage in multiple files

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by MananTank** [comment]
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by jnsdls — COMMENTED** [review]
inside team layout this still leaves `configure` tab inside in-app wallets, is that expected?

**Comment by MananTank** [comment]
yeah this just adds it to settings, will remove it in a separate PR

**Comment by MananTank** [comment]
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4675** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4676** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4675** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4676** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4675** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4677** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4677?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4676** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4675** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4677** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4677?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4676** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4675** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4677** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4677?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4676** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4675** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4677** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4677?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4676** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4675** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4677** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4677?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4676** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4675** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4680** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4680?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4677** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4677?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4676** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4675** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4680** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4680?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4677** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4677?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4676** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4675** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MananTank** [comment]
* **#4680** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4680?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4677** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4677?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4676** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4675** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4674** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4674?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4668** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4668?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#4667** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/4667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MananTank and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by jnsdls — APPROVED** [review]

**Pull request merged**
