### PR TITLE
Nft searcher

### PR DESCRIPTION
**Pull request by CalculatingZero**
## Problem solved

Created an NFT searchbar react component

## Changes made

- [ ] Added a component named NFTSearcher to enable searches for any thirdweb compatible contract
- [ ] Searchbar displays network icon and provides suggestions based on directory maintained here: https://github.com/Zerobeings/nft-indexer. Anyone can make a directory request as long as it meets the content policy requirements.

## How to test

- [ ] Automated tests: a test version of the template below has been deployed here: https://thirdweb-nftsearcher.vercel.app/. 

1. [ ] To test log in to site and switch to Frame - Testnet to search.
2. [ ] Note: The default provider of the site is the Frame - Testnet. 
3. [ ]  Search Space Fries or any test collection (by address) on the Frame - Testnet.

- [ ] Manual tests: a test template can be cloned at tested here - https://github.com/Zerobeings/thirdweb-nftsearcher

## Sample View

Screenshot 2024-02-01 at 10 28 25 PM

### CODE REVIEW

**Comment by jnsdls** [comment]
hi @CalculatingZero this is very neat!

Thank you for opening the PR, however this type of component is not something that we see as a core building block for most apps and as such does not really fit here.

This would however make a cool example of what you can build, I'm tagging in @saminacodes to coordinate potentially adding this to: https://github.com/thirdweb-example

Thanks again for your PR, samina will be in touch!

**Comment by CalculatingZero** [comment]
hi @jnsdls , thanks for letting me know.

@saminacodes if it's useful, I'd be happy to create a template with this search bar component. Please let me know what you think.

Thanks!

**Comment by saminacodes** [comment]
Wow, that would be awesome, yes please! 

I have created this empty repository for you if you could please push to here and we will review and publish:

- https://github.com/thirdweb-example/nft-searcher

Appreciate you taking the time to do this.

**Comment by CalculatingZero** [comment]
Hi @saminacodes, I have created a pull request to the empty repo:

https://github.com/thirdweb-example/nft-searcher/pull/1

Please let me know if there are any changes you would like me to make.

**Pull request closed without merging**
