### PR TITLE
add packages/chains/utils test

### PR DESCRIPTION
**Pull request by konojunya**
Add unit tests in `packages/chains/src/utils`.
スクリーンショット 2023-07-27 3 04 30

### CODE REVIEW

**Comment by jnsdls** [comment]
thx for the contribution @konojunya! this is great!

**Comment by jnsdls** [comment]
E2E failure expected as of now (fork has no access to secret key env var)

**Review by jnsdls — APPROVED** [review]
changes LGTM

**Comment by konojunya** [comment]
@jnsdls Yes, e2e failed the last time I submitted a Pull Request.
Can you re-run it?

Also, I am a service provider in Japan dealing mainly with NFT and thirdweb is a great SDK that I use in all my projects. I will be committing to it continuously in the future, so if you could give me WRITE authority as a contributor, I would be happy if you could wave the authority to me so that I can submit PR smoothly!

**Pull request merged**
