### PR TITLE
[wallet, react] Add Core wallet (Avalanche)

### PR DESCRIPTION
**Pull request by kien-ngo**
## Problem solved

Add the core.app wallet

## Changes made

- [x] Public API changes: list the public API changes made if any
- [ ] Internal API changes: explain the internal logic changes

## How to test

- [x] Automated tests: link to unit test file
- [ ] Manual tests: step by step instructions on how to test

### CODE REVIEW

**Comment by kien-ngo** [comment]
@MananTank I'm working on adding the Core wallet (from Avalanche) to our stack. I str8 up copied your code for the OKX wallet. The code is not finished yet (need to update wallet image and deep link url) however I bumped into 2 issues when testing in local with `yalc` so kinda need your help.

Definitely not urgent, pls take your time.
# Error 1
TypeError: Cannot read properties of undefined (reading 'id')
From this code: 
image
Pretty sure I added the value here: 
image



If I remove `CoreWallet.id` and hard-code it to `"coreWallet"` then it will work, however I would get the Error 2

# Error 2
erro2

Pretty confused, since I made sure all the exports/imports are identical to your code

**Comment by kien-ngo** [comment]
@MananTank lmk if you have any insight to this one ^

**Comment by MananTank** [comment]
Thanks! @kien-ngo  LGTM 🚀

**Pull request merged**
