### PR TITLE
Update webauthn to v2

### PR DESCRIPTION
**Pull request by WyattMufson**
## Problem solved

Updates to the latest version of `@passwordless-id/webauthn` which fixes issues with applications using thirdweb built with commonjs

---

## PR-Codex overview
This PR updates the `@passwordless-id/webauthn` package from version `1.6.1` to `2.1.2`, resulting in changes to the implementation of the `PasskeyWebClient` class in the `passkeys.ts` file, enhancing the registration and authentication processes.

### Detailed summary
- Updated `@passwordless-id/webauthn` dependency in `package.json` and `pnpm-lock.yaml`.
- Modified the `register` method in `PasskeyWebClient`:
  - Changed parameters to use `user` instead of `name`.
  - Accessed `clientData` and other properties from `registration.response`.
- Updated the `authenticate` method in `PasskeyWebClient`:
  - Changed parameters to use `allowCredentials` instead of `credentialId`.
  - Accessed `clientData` and other properties from `result.response`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by gregfromstl** [comment]
Hey @WyattMufson, thanks for opening this! We're actually going to be replacing this library with [Ox](https://oxlib.sh/) today which should fix this issue.

**Comment by gregfromstl** [comment]
Change of plans, going to get this merged and migrate to Ox another time

**Comment by jnsdls** [comment]
image

**Review by gregfromstl — APPROVED** [review]

**Comment by gregfromstl** [comment]
### Merge activity

* **Nov 19, 5:03 PM EST**: The merge label 'merge-queue' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=thirdweb-dev&repo=js) once it meets the requirements.

**Review by joaquim-verges — APPROVED** [review]

**Pull request merged**
