### PR TITLE
[react] Wallet UI API refactor, and other fixes

### PR DESCRIPTION
**Pull request by MananTank**
* add wallet UI API and move all the UI to wallets
* add useMagic hook
* make the wallet connection hooks - awaitable
* fix the LocalWallet.isSave()
* update copy for safe/smart wallet
* update export flow for smart wallet
* update persist: false flow for local wallet (guest mode)

TODO
* skip to connecting XYZ wallet when there's a single wallet
* add option to connect from EOA => smart wallet / safe

### CODE REVIEW

**Comment by iketw** [comment]
Should we wait to release this, it's a big change, now sure we'll have time to test it by tomorrow cc: @joaquim-verges . We can probably release wallet SDK and then do "Integrate with Connect Wallet" ?

**Comment by joaquim-verges** [comment]
@MananTank i couldnt break this - but will leave the ultimate decision to you and @iketw to merge this before stable release tomorrow or not

**Comment by joaquim-verges** [comment]
I released stable, so feel free to merge this so we can test in nightly

**Pull request merged**
