### PR TITLE
feat(wallet): add support for ecosystem wallets

### PR DESCRIPTION
**Pull request by gregfromstl**
This PR adds a new wallet type called `ecosystemWallet` to the thirdweb SDK. 

### TL;DR

- New `ecosystemWallet` added to `thirdweb` SDK.

### What changed?

- `wallets.ts`: Added new export for `ecosystemWallet`
- `ConnectButtonProps.ts`: Adjusted types to account for new wallet.
- `create-wallet.ts`: Added new case for handling `ecosystemWallet` in the `createWallet` function.
- `types.ts`: Defined new types for `ecosystemWallet`.
- Updated various internal files to integrate `ecosystemWallet` functionality.

### How to test?

- Ensure the `ecosystemWallet` can be created and connected using different account types (smart account, direct connection, etc.)
- Test the new `integratorId` feature, which allows integration with a designated ecosystem.
- Validate that autoConnect functionality works as expected with `ecosystemWallet`.

### Why make this change?

This change aims to facilitate the integration of third-party ecosystem wallets into the thirdweb SDK, improving the overall flexibility and usability of the SDK for different blockchain ecosystems.

---

---

## PR-Codex overview
This PR adds ecosystem wallet UI and ecosystemWallet to TS SDK. 

### Detailed summary
- Added ecosystem wallet UI
- Updated wallet image and homepage URLs
- Modified wallet connection options
- Updated locale types and functions
- Added new wallet entries
- Implemented ecosystem partner permissions function

> The following files were skipped due to too many changes: `packages/thirdweb/src/wallets/ecosystem/is-ecosystem-wallet.ts`, `packages/thirdweb/src/wallets/__generated__/wallet/com.payperless/index.ts`, `packages/thirdweb/src/wallets/in-app/web/lib/auth/base-login.ts`, `packages/thirdweb/src/wallets/__generated__/wallet/fun.tobi/index.ts`, `apps/playground-web/src/components/code/code-example.tsx`, `packages/thirdweb/src/wallets/in-app/core/wallet/types.ts`, `packages/thirdweb/src/react/web/ui/components/WalletImage.tsx`, `packages/thirdweb/src/react/web/wallets/in-app/useInAppWalletLocale.ts`, `packages/thirdweb/scripts/wallets/generate.ts`, `packages/thirdweb/src/react/web/ui/ConnectWallet/screens/ManageWalletScreen.tsx`, `packages/thirdweb/src/wallets/__generated__/wallet/com.safemoon/index.ts`, `packages/thirdweb/src/wallets/__generated__/wallet-ids.ts`, `packages/thirdweb/src/wallets/ecosystem/is-ecosystem-wallet.test.ts`, `packages/thirdweb/src/wallets/in-app/core/wallet/in-app-core.ts`, `packages/thirdweb/src/wallets/in-app/web/types.ts`, `packages/thirdweb/src/react/web/wallets/in-app/InAppWalletSelectionUI.tsx`, `packages/thirdweb/src/react/web/wallets/in-app/InAppWalletSocialLogin.tsx`, `packages/thirdweb/src/wallets/in-app/web/lib/auth/abstract-login.ts`, `packages/thirdweb/src/react/web/wallets/ecosystem/EcosystemWalletHeader.tsx`, `packages/thirdweb/src/wallets/ecosystem/get-ecosystem-wallet-info.test.ts`, `packages/thirdweb/src/wallets/in-app/core/authentication/type.ts`, `packages/thirdweb/src/wallets/native/create-wallet.ts`, `packages/thirdweb/src/wallets/__generated__/wallet/app.clot/image.ts`, `packages/thirdweb/src/wallets/__generated__/wallet/co.lifedefi/image.ts`, `packages/thirdweb/src/utils/fetch.ts`, `packages/thirdweb/src/wallets/__generated__/wallet-infos.ts`, `packages/thirdweb/src/wallets/in-app/web/utils/iFrameCommunication/IframeCommunicator.ts`, `packages/thirdweb/src/wallets/ecosystem/get-ecosystem-wallet-info.ts`, `packages/thirdweb/src/wallets/in-app/web/lib/auth/iframe-auth.ts`, `packages/thirdweb/src/react/web/ui/ConnectWallet/screens/PrivateKey.tsx`, `packages/thirdweb/src/wallets/in-app/web/ecosystem.ts`, `packages/thirdweb/src/wallets/in-app/web/lib/auth/index.ts`, `packages/thirdweb/src/wallets/wallet-types.ts`, `packages/thirdweb/src/wallets/create-wallet.ts`, `packages/thirdweb/src/wallets/in-app/core/constants/settings.ts`, `packages/thirdweb/src/wallets/__generated__/wallet/fun.tobi/image.ts`, `packages/thirdweb/src/react/web/utils/usePreloadWalletProviders.ts`, `packages/thirdweb/src/wallets/in-app/web/utils/iFrameCommunication/InAppWalletIframeCommunicator.ts`, `packages/thirdweb/src/react/web/wallets/ecosystem/EcosystemWalletFormUI.tsx`, `packages/thirdweb/src/react/web/wallets/ecosystem/EcosystemWalletConnectUI.tsx`, `packages/thirdweb/src/react/web/wallets/in-app/InAppWalletConnectUI.tsx`, `packages/thirdweb/src/react/web/wallets/in-app/InAppWalletPassKeyLogin.tsx`, `packages/thirdweb/src/wallets/__generated__/wallet/me.komet/image.ts`, `packages/thirdweb/src/wallets/in-app/core/wallet/index.ts`, `packages/thirdweb/src/react/web/ui/ConnectWallet/Modal/AnyWalletConnectUI.tsx`, `packages/thirdweb/src/wallets/in-app/core/wallet/ecosystem-core.ts`, `packages/thirdweb/src/wallets/__generated__/wallet/com.payperless/image.ts`, `packages/thirdweb/src/wallets/in-app/web/lib/web-connector.ts`, `packages/thirdweb/src/react/web/wallets/in-app/InAppWalletOTPLoginUI.tsx`, `packages/thirdweb/src/wallets/in-app/web/lib/in-app-account.ts`, `packages/thirdweb/src/wallets/in-app/web/utils/Storage/LocalStorage.ts`, `packages/thirdweb/src/wallets/in-app/web/lib/auth/passkeys.ts`, `packages/thirdweb/src/wallets/__generated__/getWalletInfo.ts`, `packages/thirdweb/src/react/web/wallets/shared/ConnectWalletSocialOptions.tsx`, `packages/thirdweb/src/wallets/__generated__/wallet/xyz.bonuz/image.ts`, `packages/thirdweb/src/react/web/wallets/in-app/InAppWalletFormUI.tsx`, `pnpm-lock.yaml`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by gregfromstl** [comment]
* **#3270** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/js/3270?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gregfromstl and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by joaquim-verges — APPROVED** [review]

**Pull request merged**
