### PR TITLE
[CLI] Fix "Invalid Project name" when a project with a capital letter is entered

### PR DESCRIPTION
**Pull request by aeither**

### CODE REVIEW

**Comment by nachoiacovino** [comment]
hey @aeither would you be able to add a changeset (running yarn changeset) summarizing the changes?

**Comment by aeither** [comment]
hey @nachoiacovino, changeset included.

**Comment by nachoiacovino** [comment]
you're right! thanks for the contribution we'll review it and get back to you!

**Review by joaquim-verges — APPROVED** [review]
Thanks for your contribution @aeither ! tested it and works great 👍

**Pull request merged**
