### PR TITLE
[SDK] Update Promise.all

### PR DESCRIPTION
**Pull request by kien-ngo**
## Problem solved

This is a subset of the changes from the draft PR below. Since #1648 contains too many changes I will split it up into smaller PRs
Context: https://github.com/thirdweb-dev/js/pull/1648

## Changes made

- [ ] Public API changes: list the public API changes made if any
- [x] Internal API changes: explain the internal logic changes

## How to test

- [x] Automated tests: link to unit test file
- [ ] Manual tests: step by step instructions on how to test

### CODE REVIEW

**Review by kien-ngo — COMMENTED** [review]
Thanks for this @jnsdls I will remember to create similar changeset for the upcoming ones

**Review by jnsdls — APPROVED** [review]
LGTM

**Comment by jnsdls** [comment]
will pull this and run tests locally, they're failing here because secret key env var is not available on external contributions

**Comment by kien-ngo** [comment]
> will pull this and run tests locally, they're failing here because secret key env var is not available on external contributions

I see. I'm fine but if it makes things easier for you, can we somehow "whitelist" me?

**Comment by jnsdls** [comment]
> > will pull this and run tests locally, they're failing here because secret key env var is not available on external contributions
> 
> I see. I'm fine but if it makes things easier for you, can we somehow "whitelist" me?

you should be able to re-clone the repo directly (instead of a fork) since you are no longer `external` and at that point it should work.

also tests pass fine -> merging

**Pull request merged**
