### PR TITLE
nft-drop prepareClaim -> public

### PR DESCRIPTION
**Pull request by jakeloo**

### CODE REVIEW

**Comment by jnsdls** [comment]
@joaquim-verges we should look at just handling this predictably everywhere, we have a bunch of places where `prepareClaim` is public and others where it's not, I don't really understand the reasoning (if any) behind it

**Review by jnsdls — CHANGES_REQUESTED** [review]
definitely needs a changeset

**Comment by joaquim-verges** [comment]
Was private initially in pre builts, but had to make it public for extensions. Just need to delete the top level ones in pre built. They all call the same helper function under the hood.

People should use `contract(.erc721/.erc1155).claimConditions.prepareClaim(...)`

Lets not make this one public, should be deleted instead

**Review by joaquim-verges — CHANGES_REQUESTED** [review]
Not needed

**Pull request closed without merging**
