### PR TITLE
Adds custom logo to social login modal

### PR DESCRIPTION
**Pull request by gregfromstl**
All screenshots are taken with the logo at its maximum height

Screenshot 2024-05-14 at 5 13 43 PM
Screenshot 2024-05-14 at 5 13 53 PM
IMG_4458

---

## PR-Codex overview
This PR enhances the In-App Wallet feature by allowing users to set a custom logo for the social login modal.

### Detailed summary
- Added the ability to set a custom logo for the social login modal in the In-App Wallet feature
- Updated modal heights in UI components
- Added warning for improperly configured images
- Improved UI layout in Wallet Selector component

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by joaquim-verges** [comment]
@gregfromstl still seeing the skeleton off-center while the image is loading. you can see it easily with this metadata
```ts
metadata: {
								image: {
									height: 100,
									width: 100,
									src: "https://source.unsplash.com/100x100/?cat",
								},
							},
```

**Comment by joaquim-verges** [comment]
also you should remove the 16px vertical padding around the image container, makes it hard to scale the user's image properly, adds too much spacing around

**Comment by joaquim-verges** [comment]
and last thing - i really wish i could omit 'width' so it just goes full width. most of the time i just want to control the height

**Comment by gregfromstl** [comment]
> th. most of the time i just want to control the

Okay I think I finally got this one, the unloaded image was still hiding on the page

**Comment by gregfromstl** [comment]
> @gregfromstl still seeing the skeleton off-center while the image is loading. you can see it easily with this metadata
> 
> ```ts
> metadata: {
>   image: {
> 	  height: 100,
> 	  width: 100,
> 	  src: "https://source.unsplash.com/100x100/?cat",
>   },
> },
> ```

Okay I think I finally got this one, the unloaded image was still hiding on the page

**Comment by gregfromstl** [comment]
> and last thing - i really wish i could omit 'width' so it just goes full width. most of the time i just want to control the height

@joaquim-verges what if they're trying to add an icon? I guess with the max width and height it should just scale itself?

**Review by joaquim-verges — APPROVED** [review]

**Pull request merged**
