### PR TITLE
[SDK] Perf improv for drop-claim-conditions

### PR DESCRIPTION
**Pull request by kien-ngo**
## Problem solved

- Continuous work for #1648 
- This should have a slightly positive effect on #1510 

## Changes made

- [ ] Public API changes: list the public API changes made if any
- [x] Internal API changes: explain the internal logic changes

## How to test

- [x] Automated tests: link to unit test file
- [ ] Manual tests: step by step instructions on how to test

### CODE REVIEW

**Comment by kien-ngo** [comment]
@joaquim-verges I'm working on improving the code for issue #1510 and as part of the PR #1648 

Not sure why we are awaiting these "Read" function calls without using their results. Possible to remove?
Code location: https://github.com/thirdweb-dev/js/blob/main/packages/sdk/src/evm/core/classes/drop-claim-conditions.ts#L350-L378
image

**Comment by joaquim-verges** [comment]
@kien-ngo we use them to check for errors, if they error out we show the corresponding ineligibility reasons

**Review by joaquim-verges — APPROVED** [review]
lg

**Comment by kien-ngo** [comment]
Gotcha. Ty

**Pull request merged**
