### PR TITLE
[Storage] - allow uploading the same file multiple times in uploadBatch if it is *the same file*

### PR DESCRIPTION
**Pull request by jnsdls**

### CODE REVIEW

**Comment by jnsdls** [comment]
@adam-maj just tagged so u see it

**Comment by nachoiacovino** [comment]
does this make it so it works the same as before or we're making it so we're only uploading it once and using the same URI for both?

**Comment by jnsdls** [comment]
> does this make it so it works the same as before or we're making it so we're only uploading it once and using the same URI for both?

the second one of those ;)

**Comment by nachoiacovino** [comment]
> > does this make it so it works the same as before or we're making it so we're only uploading it once and using the same URI for both?
> 
> the second one of those ;)

nice

**Pull request merged**
