### PR TITLE
Fix exception on chain with unknown chainId

### PR DESCRIPTION
**Pull request by MananTank**
## PR-Codex overview
The focus of this PR is to fix an exception when passing an unknown `chainId` to `ConnectButton`.

### Detailed summary
- Fixed exception handling in `NetworkSelector.tsx`
- Improved error handling in `utils.ts`
- Added `createChainMetadata` function for creating chain metadata

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by MananTank** [comment]
creating a dev build for now - need to test this further / modify

**Comment by MananTank** [comment]
we should also add the icon to `Chain` object type - a user can pass the icon to `defineChain` but it does not make it's way to `Chain`

**Review by jnsdls — APPROVED** [review]
I really don't like standardizing on the `chainmetadata` type rather than on the `chain` type (and adding anything it's missing in there)

that said this should be an internal change we can make later so it should not be a blocker

**Pull request merged**
