### PR TITLE
[SDK] ERC721: Add option to use getOwned and getAll without loading the nfts's metadata

### PR DESCRIPTION
**Pull request by kien-ngo**
## Problem solved

ERC721: Add option to use getOwned and getAll without loading the nfts's metadata
This PR is only for RC721. Should everything check out I will work on a version for ERC1155

# New functions
- [x] `getWithoutMetadata` | similar to `get()`
- [x] `getAllWithoutMetadata` | similar to `getAll()`
- [x] `getOwnedWithoutMetadata` | similar to `getOwned()`

# Unit tests added for:
- [ ] getWithoutMetadata
- [x] getAllWithoutMetadata
- [ ] getOwnedWithoutMetadata

## Changes made

- [x] Public API changes: list the public API changes made if any
- [ ] Internal API changes: explain the internal logic changes

## How to test

- [x] Automated tests: link to unit test file
- [ ] Manual tests: step by step instructions on how to test

### CODE REVIEW

**Comment by kien-ngo** [comment]
@joaquim-verges We discussed about this option a few weeks ago. Are you cool with the names of these functions?

**Comment by joaquim-verges** [comment]
Was thinking more about it, and I think we actually can keep a single function and still get nice return types with some generics.

Basically return `NFTWithoutMetadata[]` only if the optional flag is set, otherwise regular `NFT[]`.

Lmk if you want to take a stab at this, other I can help next week

**Comment by kien-ngo** [comment]
I will give it a try. But will have some more questions to ask ^

**Comment by kien-ngo** [comment]
CLosing this. Will open a new PR

**Pull request closed without merging**
