### PR TITLE
[wallets, react] add bitkeep wallet

### PR DESCRIPTION
**Pull request by abner-jie**

### CODE REVIEW

**Comment by iketw** [comment]
> Hey @abner-jie - Thanks for the PR, We are very excited to get this merged!
> 
> Everything looks good, There's just one issue: When I connect to BitKeep wallet using the QR scan - I am not able to switch chain - if the chain is not added in app. It gets stuck in loading state.
> 
> Example:
> 
> image
> Can you look into this? Looks like an issue in Bitkeep iOS app.
> 
> Also - When I switch chain, I get a popup in Chinese in iOS app:
> 
> image

@abner-jie did you have time to take a look into this?

**Comment by abner-jie** [comment]
> > Hey @abner-jie - Thanks for the PR, We are very excited to get this merged!嘿 - 感谢您的公关，我们很高兴能合并！
> > Everything looks good, There's just one issue: When I connect to BitKeep wallet using the QR scan - I am not able to switch chain - if the chain is not added in app. It gets stuck in loading state.一切看起来都不错，只有一个问题：当我使用 QR 扫描连接到 BitKeep 钱包时 - 我无法切换链 - 如果链未添加到应用程序中。它卡在加载状态。
> > Example: 例：
> > image
> > Can you look into this? Looks like an issue in Bitkeep iOS app.
> > 你能调查一下吗？看起来像Bitkeep iOS应用程序中的问题。Also - When I switch chain, I get a popup in Chinese in iOS app:另外 - 当我切换链时，我在 iOS 应用程序中收到一个中文弹出窗口：
> > image
> 
> @abner-jie did you have time to take a look into this?你有时间研究一下吗？

Very sorry, we have reproduced this issue and are working hard to resolve it

**Comment by abner-jie** [comment]
> > Hey @abner-jie - Thanks for the PR, We are very excited to get this merged!
> > Everything looks good, There's just one issue: When I connect to BitKeep wallet using the QR scan - I am not able to switch chain - if the chain is not added in app. It gets stuck in loading state.
> > Example:
> > image
> > Can you look into this? Looks like an issue in Bitkeep iOS app.
> > Also - When I switch chain, I get a popup in Chinese in iOS app:
> > image
> 
> @abner-jie did you have time to take a look into this?
Very sorry, we have reproduced this issue and are working hard to fix it

**Comment by joaquim-verges** [comment]
@abner-jie any updates here? would love to get this in!

**Comment by MananTank** [comment]
Hi @abner-jie, Any Updates here?

**Comment by abner-jie** [comment]
Hi @MananTank,  We are very sorry, but we plan to fix the problem in mid August. Please be patient and wait

**Pull request closed without merging**
