### PR TITLE
[wallet, react] Add Coin98 Wallet

### PR DESCRIPTION
**Pull request by kien-ngo**
## Problem solved

Give it a try: https://coin98-wallet.vercel.app/
- [x] Browser extension
- [x] Deeplink for mobile

## Changes made

- [x] Public API changes: list the public API changes made if any
- [ ] Internal API changes: explain the internal logic changes

## How to test

- [ ] Automated tests: link to unit test file
- [x] Manual tests: step by step instructions on how to test

### CODE REVIEW

**Comment by kien-ngo** [comment]
@ MananTank their deeplink doesn't seem to work, I have reached out to their Discord
https://docs.coin98.com/developer-guide/deeplink

Also the deeplink has a `chainId` parameter. Checking with them if it's optional, otherwise will need to get the chainId before calling the URL

**Comment by kien-ngo** [comment]
@MananTank this PR is ready to be reviewed.
I deployed a website for you too ^: https://coin98-wallet.vercel.app/

**Comment by MananTank** [comment]
Thanks @kien-ngo!

**Pull request merged**
