### PR TITLE
[REACT] Add custom links to connect wallet details modal

### PR DESCRIPTION
**Pull request by dlather**
## Problem solved

Add support for adding custom links, which can be used to add on ramp functionality

## Changes made

- [ ] Public API changes: list the public API changes made if any
- [ ] Internal API changes: explain the internal logic changes

## How to test

- [ ] Automated tests: link to unit test file
- [ ] Manual tests: step by step instructions on how to test

### CODE REVIEW

**Comment by warengonzaga** [comment]
Hey @jnsdls can you take a look here? The github action is failing.

**Comment by warengonzaga** [comment]
Hey, @jnsdls and @MananTank can you take a look into it?

**Comment by dlather** [comment]
Would be great to get a dev version released atleast.

**Comment by MananTank** [comment]
@dlather Thanks for the contribution! 

Instead of just rendering custom links - I've created https://github.com/thirdweb-dev/js/pull/2252 to allow rendering any custom UI in the ConnectWallet details modal.

**Pull request closed without merging**
